language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t seungmoolee/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true seungmoolee/react-test-app npm test

after_success:
  - docker build -t seungmoolee/docker-frontend ./frontend
  - docker build -t seungmoolee/docker-backend ./backend
  - docker build -t seungmoolee/docker-nginx ./nginx
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push seungmoolee/docker-frontend
  - docker push seungmoolee/docker-backend
  - docker push seungmoolee/docker-nginx